[[redirects]]
  from = "/api/*"
  to = "http://159.223.29.178/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/projetos"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/sobre"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200