redirects = [
  {from = "/api/*", to = "http://159.223.29.178/api/:splat", status = 200, , force = true},
  {from = "/", to = "/index.html", status = 200 },
  {from = "/projetos", to = "/index.html", status = 200 },
  {from = "/projetos/*", to = "/index.html", status = 200 },
  {from = "/sobre", to = "/index.html", status = 200 }]